apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: koor-release
  namespace: koor-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: koor-release
      version: v1.12.0
  interval: 1m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: koor-ceph
  valuesFrom:
  - kind: ConfigMap
    name: koor-ceph-helm-chart-value-overrides
    valuesKey: values.yaml
