apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: kubeflow-pipelines
  namespace: kubeflow
spec:
  bucketName: kubeflow-pipelines
  storageClassName: ceph-bucket
