apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-team-1-bucket-access
  namespace: team-1
spec:
  selector:
    matchLabels:
      add-team-1-bucket-access: "true"
  desc: "Add team-1-bucket access"
  envFrom:
    - configMapRef:
        name: team-1-bucket
    - secretRef:
        name: team-1-bucket