apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-bucket-config
  namespace: team-1
spec:
  selector:
    matchLabels:
      add-bucket-config: "true"
  desc: "Add rook bucket"
  envFrom:
    - configMapRef:
        name: team-1-bucket
    - secretRef:
        name: team-1-bucket