apiVersion: sources.knative.dev/v1alpha1
kind: CephSource
metadata:
  name: ml-ceph-source
  namespace: default
spec:
  port: "8888"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
---
apiVersion: v1
kind: Service
metadata:
  name: ml-ceph-source-svc
  namespace: default
spec:
  selector:
    eventing.knative.dev/sourceName: ml-ceph-source
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
