apiVersion: ceph.rook.io/v1
kind: CephBucketTopic
metadata:
  name: ml-topic
  namespace: default
spec:
  objectStoreName: ceph-objectstore
  objectStoreNamespace: rook-ceph
  endpoint:
    http:
      uri: http://ml-ceph-source-svc.default.svc:80
      disableVerifySSL: true
      sendCloudEvents: true
---
apiVersion: ceph.rook.io/v1
kind: CephBucketNotification
metadata:
  name: ml-notification
  namespace: default
spec:
  topic: ml-topic
  events:
  - s3:ObjectCreated:*
