apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: knative-ml-inputs
  labels:
    bucket-notification-my-notification: my-notification
spec:
  generateBucketName: ml-inputs
  storageClassName: ceph-bucket
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: knative-ml-outputs
spec:
  generateBucketName: ml-outputs
  storageClassName: ceph-bucket
