apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    autoscaler:
      # Helps with debugging
      scale-to-zero-pod-retention-period: "20s"
    domain:
      "knative.koor.dev": ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
  services:
    - name: kourier
      # Override annotations for the kourier service
      annotations:
        # A provider-specific annotation is necessary to access the functions using a load balancer
        # For Hetzner it is:
        load-balancer.hetzner.cloud/name: "koor-demo-kourier"
