apiVersion: v1
kind: Namespace
metadata:
  name: busybot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybot-cephfs-pvc
  namespace: busybot
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
  storageClassName: ceph-filesystem
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybot
  namespace: busybot
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:          
      labels:
        app: busybot
        cron: busybot
    spec:
      template:
        spec:
          containers:
          - name: busybot-cont
            image: alpine:3.18.4
            imagePullPolicy: IfNotPresent
            env:
            - name: STORE
              value: /store
            - name: COUNT
              value: "5"
            - name: DEL_COUNT
              value: "2"
            - name: SIZE
              value: 50M
            volumeMounts:
            - name: busybot-store
              mountPath: /store
            command:
            - /bin/sh
            - -c
            - |
              
              echo Reading directory
              echo "Number of files: $(ls $STORE | wc -l)"
              
              # Read $COUNT random files from store and calculate md5
              ls $STORE | shuf -n $COUNT | while read file
              do
                md5sum $STORE/$file
              done

              # Write $COUNT random files from store
              shuf -n $COUNT -i 0-99 | while read file
              do
                dd if=/dev/urandom of=/tmp/file bs=$SIZE count=1
                md5=$(md5sum /tmp/file | awk '{ print $1 }')
                filename=$(printf "%02d" $file)
                echo Writing $filename
                rm -f $STORE/$filename-*
                mv /tmp/file $STORE/$filename-$md5
              done

              # Delete $DEL_COUNT random files from store
              ls $STORE | shuf -n $DEL_COUNT | while read file
              do
                echo Deleting $file
                rm $STORE/$file
              done
          restartPolicy: Never
          volumes:
          - name: busybot-store
            persistentVolumeClaim:
              claimName: busybot-cephfs-pvc
              readOnly: false
