# this will deploy all yamls present in koor-ceph path
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: koor-ceph
  namespace: flux-system
spec:
  interval: 30m
  path: ./flux/flux-system/koor-ceph
  prune: true # remove any elements later removed from the above path
  timeout: 10m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
      #  healthChecks:
      #    - apiVersion: apiextensions.k8s.io/v1
      #      kind: CustomResourceDefinition
      #      name: cephblockpools.ceph.rook.io
