apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knative-pc-cephfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 11Gi
  storageClassName: ceph-filesystem