apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: koor-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: koor-release
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: koor-release
      version: v1.12.0
  interval: 1m0s
